/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem.ui;
import javax.swing.table.DefaultTableModel;
import librarymanagementsystem.models.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Alvin
 */
public class LibraryUI extends javax.swing.JFrame {

    /**
     * Creates new form LibraryUI
     */
    public LibraryUI() {
    initComponents();
    setLocationRelativeTo(null);
    setTitle("Management Perpustakaan PINJAMBUKU");
    librarymanagementsystem.services.LibraryService.loadData();
    updateBookTable();
    updateMemberTable();
    updateTotalBooksLabel();
    updateTotalMembersLabel();
    updateMemberComboBox();
    updateBorrowingTable();


    removeBookButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeBookButtonActionPerformed(evt);
        }
    });

    removeMemberButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeMemberButtonActionPerformed(evt);
        }
    });

    borrowBookButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            borrowBookButtonActionPerformed(evt);
        }
    });

    returnBookButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            returnBookButtonActionPerformed(evt);
        }
    });

    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
            librarymanagementsystem.services.LibraryService.saveData();
            System.exit(0);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalBooksLabel = new javax.swing.JLabel();
        totalMembersLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        borrowingTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        bookIDField = new javax.swing.JTextField();
        bookTitleField = new javax.swing.JTextField();
        javax.swing.JButton addBookButton = new javax.swing.JButton();
        removeBookButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bookTypeComboBox = new javax.swing.JComboBox<>();
        memberComboBox = new javax.swing.JComboBox<>();
        borrowBookButton = new javax.swing.JButton();
        returnBookButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        memberIDField = new javax.swing.JTextField();
        memberNameField = new javax.swing.JTextField();
        addMemberButton = new javax.swing.JButton();
        removeMemberButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to PINJAMBUKU");

        totalBooksLabel.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        totalBooksLabel.setText("Total Books: 0");

        totalMembersLabel.setFont(new java.awt.Font("Sans Serif Collection", 0, 18)); // NOI18N
        totalMembersLabel.setText("Total Members: 0");

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("(Perpustakaan Inspiratif Nyaman Jadi Aman Meminjam Buku Untuk Kamu)");

        borrowingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Buku", "Judul Buku", "Dipinjam oleh"
            }
        ));
        jScrollPane3.setViewportView(borrowingTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalMembersLabel)
                        .addGap(111, 111, 111))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {totalBooksLabel, totalMembersLabel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBooksLabel)
                    .addComponent(totalMembersLabel))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Main Menu", jPanel1);

        addBookButton.setText("Add Book");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        removeBookButton.setText("Remove Book");
        removeBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookButtonActionPerformed(evt);
            }
        });

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title"
            }
        ));
        jScrollPane1.setViewportView(bookTable);

        jLabel5.setText("ID");

        jLabel6.setText("Title");

        bookTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book", "Novel", "Textbook" }));
        bookTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTypeComboBoxActionPerformed(evt);
            }
        });

        memberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih member" }));
        memberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberComboBoxActionPerformed(evt);
            }
        });

        borrowBookButton.setText("Borrow Book");
        borrowBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBookButtonActionPerformed(evt);
            }
        });

        returnBookButton.setText("Return Book");
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(borrowBookButton)
                        .addGap(18, 18, 18)
                        .addComponent(returnBookButton))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookTitleField)
                            .addComponent(bookIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(removeBookButton)
                            .addGap(11, 11, 11))
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bookTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(memberComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addBookButton, removeBookButton});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(bookTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookButton)
                    .addComponent(removeBookButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowBookButton)
                    .addComponent(returnBookButton))
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Book Management", jPanel2);

        memberNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberNameFieldActionPerformed(evt);
            }
        });

        addMemberButton.setText("Add Member");
        addMemberButton.setFocusable(false);
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed(evt);
            }
        });

        removeMemberButton.setText("Remove Member");
        removeMemberButton.setFocusable(false);
        removeMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMemberButtonActionPerformed(evt);
            }
        });

        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane2.setViewportView(memberTable);

        jLabel3.setText("ID");

        jLabel4.setText("Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(addMemberButton)
                                .addGap(18, 18, 18)
                                .addComponent(removeMemberButton))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(memberNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(memberIDField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(187, 187, 187))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addMemberButton, removeMemberButton});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMemberButton)
                    .addComponent(removeMemberButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Member Management", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tab1\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberNameFieldActionPerformed

    private void addMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtonActionPerformed
    System.out.println("addMemberButtonActionPerformed dipanggil");
    String id = memberIDField.getText().trim();
    String name = memberNameField.getText().trim();

    if (id.isEmpty() || name.isEmpty()) {
        System.out.println("Validasi gagal: ID atau Name kosong");
        JOptionPane.showMessageDialog(this, "Tolong diisi semua ya :)", "Bro ada yang belum diisi", JOptionPane.ERROR_MESSAGE);
        memberIDField.requestFocusInWindow();
    } else {
        System.out.println("Validasi sukses, menambah member: " + id + ", " + name);
        librarymanagementsystem.services.LibraryService.addMember(id, name);
        updateMemberTable();
        updateTotalMembersLabel();
        updateMemberComboBox(); // Tambah ini untuk memperbarui combo box
        memberIDField.setText("");
        memberNameField.setText("");
        memberIDField.requestFocusInWindow();
    }
    }//GEN-LAST:event_addMemberButtonActionPerformed

    private void updateMemberTable() {
    DefaultTableModel model = (DefaultTableModel) memberTable.getModel();
    model.setRowCount(0);
    for (Member member : librarymanagementsystem.services.LibraryService.getMembers()) {
        model.addRow(new Object[]{member.getId(), member.getName()});
    }
}
    
    private void updateTotalMembersLabel() {
    totalMembersLabel.setText("Total Members: " + librarymanagementsystem.services.LibraryService.getTotalMembers());
}
    
    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonActionPerformed
    System.out.println("addBookButtonActionPerformed dipanggil");
    String id = bookIDField.getText().trim();
    String title = bookTitleField.getText().trim();
    String type = (String) bookTypeComboBox.getSelectedItem();

    if (id.isEmpty() || title.isEmpty()) {
        System.out.println("Validasi gagal: ID atau Title kosong");
        bookIDField.requestFocusInWindow();
    } else {
        System.out.println("Validasi sukses, menambah buku: " + id + ", " + title + ", " + type);
        librarymanagementsystem.services.LibraryService.addBook(id, title, type);
        updateBookTable();
        updateTotalBooksLabel();
        bookIDField.setText("");
        bookTitleField.setText("");
        bookIDField.requestFocusInWindow();
    }
    }//GEN-LAST:event_addBookButtonActionPerformed

    private void bookTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTypeComboBoxActionPerformed
    String id = bookIDField.getText().trim();
    String title = bookTitleField.getText().trim();
    String type = (String) bookTypeComboBox.getSelectedItem();

    if (id.isEmpty() || title.isEmpty()) {
        bookIDField.requestFocusInWindow();
    } else {
        librarymanagementsystem.services.LibraryService.addBook(id, title, type);
        updateBookTable();
        updateTotalBooksLabel();
        bookIDField.setText("");
        bookTitleField.setText("");
    }
    }//GEN-LAST:event_bookTypeComboBoxActionPerformed

    private void removeBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookButtonActionPerformed
    int selectedRow = bookTable.getSelectedRow();
    System.out.println("Baris yang dipilih saat remove book: " + selectedRow); // Ubah "remove member" menjadi "remove book"
    
    if (selectedRow == -1) {
        System.out.println("Tidak ada buku dipilih, tidak melakukan apa-apa");
        return;
    }

    String id = (String) bookTable.getValueAt(selectedRow, 0); // Kolom ID
    System.out.println("Menghapus buku dengan ID: " + id);
    librarymanagementsystem.services.LibraryService.removeBook(id);
    updateBookTable();
    updateTotalBooksLabel();
    bookTable.clearSelection();
    bookIDField.requestFocusInWindow();
    }//GEN-LAST:event_removeBookButtonActionPerformed

    private void removeMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMemberButtonActionPerformed
    int selectedRow = memberTable.getSelectedRow();
    System.out.println("Baris yang dipilih saat remove member: " + selectedRow);

    String id = (String) memberTable.getValueAt(selectedRow, 0); // Kolom ID
    System.out.println("Menghapus member dengan ID: " + id);
    librarymanagementsystem.services.LibraryService.removeMember(id);
    updateMemberTable();
    updateTotalMembersLabel();
    updateMemberComboBox(); // Tambah ini untuk memperbarui combo box
    memberTable.clearSelection();
    memberIDField.requestFocusInWindow();
    }//GEN-LAST:event_removeMemberButtonActionPerformed

    private void memberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memberComboBoxActionPerformed

    private void borrowBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBookButtonActionPerformed
    int selectedRow = bookTable.getSelectedRow();

    String bookId = (String) bookTable.getValueAt(selectedRow, 0);
    String memberSelection = (String) memberComboBox.getSelectedItem();

    String memberId = memberSelection.split(" - ")[0];
    librarymanagementsystem.services.LibraryService.borrowBook(bookId, memberId);
    updateBorrowingTable();
    updateBookTable();
    }//GEN-LAST:event_borrowBookButtonActionPerformed

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
    int selectedRow = bookTable.getSelectedRow();
        
    String bookId = (String) bookTable.getValueAt(selectedRow, 0);
    librarymanagementsystem.services.LibraryService.returnBook(bookId);
    updateBorrowingTable();
    }//GEN-LAST:event_returnBookButtonActionPerformed
    
    private void updateBookTable() {
    DefaultTableModel model = (DefaultTableModel) bookTable.getModel();
    model.setRowCount(0);
    for (Book book : librarymanagementsystem.services.LibraryService.getBooks()) {
        model.addRow(new Object[]{book.getId(), book.getDetails()});
    }
}

    private void updateTotalBooksLabel() {
        totalBooksLabel.setText("Total Books: " + librarymanagementsystem.services.LibraryService.getTotalBooks());
    }
    
   private void updateMemberComboBox() {
    memberComboBox.removeAllItems();
    memberComboBox.addItem("Pilih member");
    for (Member member : librarymanagementsystem.services.LibraryService.getMembers()) {
        memberComboBox.addItem(member.getId() + " - " + member.getName());
    }
}

private void updateBorrowingTable() {
    DefaultTableModel model = (DefaultTableModel) borrowingTable.getModel();
    model.setRowCount(0);
    for (Book book : librarymanagementsystem.services.LibraryService.getBooks()) {
        if (book.isBorrowed()) {
            model.addRow(new Object[]{book.getId(), book.getTitle(), book.getBorrower().getName()});
        }
    }
}

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMemberButton;
    private javax.swing.JTextField bookIDField;
    private javax.swing.JTable bookTable;
    private javax.swing.JTextField bookTitleField;
    private javax.swing.JComboBox<String> bookTypeComboBox;
    private javax.swing.JButton borrowBookButton;
    private javax.swing.JTable borrowingTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> memberComboBox;
    private javax.swing.JTextField memberIDField;
    private javax.swing.JTextField memberNameField;
    private javax.swing.JTable memberTable;
    private javax.swing.JButton removeBookButton;
    private javax.swing.JButton removeMemberButton;
    private javax.swing.JButton returnBookButton;
    private static javax.swing.JLabel totalBooksLabel;
    private static javax.swing.JLabel totalMembersLabel;
    // End of variables declaration//GEN-END:variables
}
